algoritmo "toque-medio"

var
     codigo, quantidade : inteiro
     valor,valor_total: real

inicio
         escrevaL("Estoque Medio")
         escrevaL("Codigo Peça")
         leia(codigo)
         escreval("Valor da peça")
         leia(valor)
         escreval("Insira a nota Quamtidade de peça 1:")
         leia(Quantidade)
         
         valor_total <-(quantidade * valor)
         escreval("O codido da peça ", codigo, "seu valor total é", valor_total)
         
fimalgoritmo
